import NavBar from "./navBar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    //<html lang="en">
    <div>
      <NavBar />
      <body>{children}</body>
      </div>
    //</html>
  )
}
